### ISSUE TITLE
Multi-world Prefix Support

### ISSUE THREAD

**Issue by Tsuser1** [J4D3N/GameRanks#1]
When a player ranks up in the main world and they for instance go to the nether their prefix is not correct to the rank they are at. It is fixed by the player rejoining in the glitched prefix world.

**Comment by J4D3N** [comment]
Can you tell me the plugins you used with it?

I need to know which plugins you used:
- Perissions plugin
- Chat plugin

**Comment by J4D3N** [comment]
#86cd2a4628d3cc0ad8eac0c450b352c62b0ff45a
