### ISSUE TITLE
Add "development" branch to repository

### ISSUE THREAD

**Issue by Tsuser1** [J4D3N/GameRanks#12]
There should be a development branch for experimental features to get sandboxed (things like the prefix fix, this was actually a broken update that would've gotten caught before being added to the master branch).

**Comment by J4D3N** [comment]
Okay, I can agree to this.

**Comment by J4D3N** [comment]
On second thought, I'd be easier to have a single branch and release multi-compatible updates. It'll be easier to track personally.
