### ISSUE TITLE
Paging Commit

### ISSUE THREAD

**Issue by J4D3N** [J4D3N/GameRanks#19]
The paging commit doesn't support the current basic convention also it provides some inefficiency when providing unneeded generation of  arrays and type conversion.

**Comment by Tsuser1** [comment]
Unbelievably that piece of code is the result after two hours of testing, will optimize where possible.

**Comment by J4D3N** [comment]
Looking into myself, should be fine soon.

**Comment by Tsuser1** [comment]
Type cast looks as if that's as optimized as possible. Submitting patch for other optimizations. Help needed on language file implementation.

**Comment by J4D3N** [comment]
Just finished optimising to the best I can do right now.
