### ISSUE TITLE
Automatic Updating

### ISSUE THREAD

**Issue by J4D3N** [J4D3N/GameRanks#28]
As you mentioned automatic updating might be a good feature to include.

**Comment by Tsuser1** [comment]
https://github.com/gravitylow/Updater

Potentially better than what we would come up with.

**Comment by J4D3N** [comment]
Very true, that looks like something to include in the next version.

**Comment by Tsuser1** [comment]
Introduced feature in the first 1.1.2 INDEV PreRelease/BETA build.

*Closing ticket - Resolved*
