### ISSUE TITLE
World prefix fix non-functional

### ISSUE THREAD

**Issue by Tsuser1** [J4D3N/GameRanks#3]
The update for the per-world prefix bug did not work and has actually completely broken prefixes! Prefixes simply do not appear. There is no error in the console.

**Comment by Tsuser1** [comment]
Referencing solution https://www.spigotmc.org/threads/setting-global-suffix-prefix-with-vault.184175/

Call "null" as the world in the set prefix instead of looping through all worlds (which I can admit, is very logical. Null makes no sense unless you really think about it.)

Also, please start keeping a pre-built jar in the repository, compiling every update is quite tedious.

**Comment by Tsuser1** [comment]
Tested fix in post, fully functional.
Replace for loops with prefix/suffix set calls to world null.

**Comment by J4D3N** [comment]
I guess it makes sense, null for a non-set world specific prefix/suffix makes more sense for a global aspect. I'll commit this in asap. Will re-release as current version since it's a small patch.

**Comment by J4D3N** [comment]
Patched and compiled, releases will be in the GitHub releases section. Feel free to download that instead of compiling manually.
