### ISSUE TITLE
GameRanks v1.1.1

### ISSUE THREAD

**Issue by J4D3N** [J4D3N/GameRanks#5]
In this update I plan to introduce 3 new features:
- [x] More flexible rank setting commands.
- [x] Permissions per rank.
- [x] Pages on ranks list.

**Comment by Tsuser1** [comment]
How about on rankup we do `sender.hasPermission("gameranks." + newRank.getName().toLowerCase());`?

**Comment by J4D3N** [comment]
Good idea, will start working on a commit for Tuesday.

**Comment by Tsuser1** [comment]
Define "more flexible rank setting commands"

**Comment by J4D3N** [comment]
It was a planned feature to allow administrators to set players ranks easily. Without having to rank them down and down etc...
