### ISSUE TITLE
Optimization on /ranks

### ISSUE THREAD

**Issue by Tsuser1** [J4D3N/GameRanks#6]
The usage of this to find if a rank exists:
`				for(Rank rankSearch : rankManager.getRanks()) {
					if(rankSearch.getName().equalsIgnoreCase(arg)) {
						rank = rankSearch;
						break;
					}
				}`
Is extremely unoptimized, instead use a `plugin.getConfig().getConfigurationSection("ranks").contains(arg);`, it also leads to less calls.

**Comment by Tsuser1** [comment]
``

**Comment by Tsuser1** [comment]
That moment when you accidentally hit close and comment.

**Comment by J4D3N** [comment]
I thought it'd be easier to cycle through the array rather than use the disk read, which is usually far more limiting than memory.

**Comment by Tsuser1** [comment]
Actually, the config is held in memory, that is why a `plugin.saveConfig();` is even there, it writes changes from memory to disk.

**Comment by J4D3N** [comment]
That array is required anyway to store ranks, surely it'd be easier for Java to cycle through a small object array than a large config array stored in a map etc..?

**Comment by Tsuser1** [comment]
Usage case in this instance is correct.
